version: '3.7'

services:

  simulator:
    env_file: .env
    container_name: simulator
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /baseroute:/src/app
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true